name: Template
author: PlugMania
main: com.github.plugmania.template.Template
version: 0.0.1
description: Template.
commands:
  template:
    usage: /template
    description: Shows default help and info
